# This file was generated by GoReleaser. DO NOT EDIT.
cask "weft" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "71524ed4f3915d4db7e9dec90830ec74b3e2c1c99ac56a670e8bc7cc29732dcb"
      url "https://github.com/HeoJeongBo/weft/releases/download/v#{version}/weft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "57ed6f5cbc1b7a21d8ed4246aa5c6b798fc792157cf8eb2f61c299cc3a332398"
      url "https://github.com/HeoJeongBo/weft/releases/download/v#{version}/weft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d2e75c037fe291589cc5828d7a4110cc1c6a1eaf12475088ee7d25d2359a2a60"
      url "https://github.com/HeoJeongBo/weft/releases/download/v#{version}/weft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "57aa93724bcac918e7b157f257213f0f1583bb8c48cda2ec3ca779b10f23c4ac"
      url "https://github.com/HeoJeongBo/weft/releases/download/v#{version}/weft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "weft"
  desc "Orchestrate parallel Claude Code sessions across git worktrees + devcontainers"
  homepage "https://github.com/HeoJeongBo/weft"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "weft"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/weft"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    weft also needs Docker (Docker Desktop, OrbStack, or colima) and the
    Dev Container CLI, which are not Homebrew formulae:

      npm install -g @devcontainers/cli

    Run `weft doctor` to verify your environment.
  EOS
end
