# This file was generated by GoReleaser. DO NOT EDIT.
cask "weft" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "6e2239283a66c60146124c4b4ce0b08f28376bd3198cb5207be6a87a340ba970"
      url "https://github.com/HeoJeongBo/weft/releases/download/v#{version}/weft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "034dc5932423ffa17dc1b41398bce68d58d7fb2a8a62ab37c03be416269ba30e"
      url "https://github.com/HeoJeongBo/weft/releases/download/v#{version}/weft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "643e8852d8d81457b0f96f44b2f628e0428da06696cbd6eddca745fcd38c1a82"
      url "https://github.com/HeoJeongBo/weft/releases/download/v#{version}/weft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "986662e7a199514f1e060fcdcc38d142cd6dd8d0f99fa35b08108c7a81c3ec38"
      url "https://github.com/HeoJeongBo/weft/releases/download/v#{version}/weft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "weft"
  desc "Orchestrate parallel Claude Code sessions across git worktrees + devcontainers"
  homepage "https://github.com/HeoJeongBo/weft"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "weft"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/weft"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    weft also needs Docker (Docker Desktop, OrbStack, or colima) and the
    Dev Container CLI, which are not Homebrew formulae:

      npm install -g @devcontainers/cli

    Run `weft doctor` to verify your environment.
  EOS
end
