# This file was generated by GoReleaser. DO NOT EDIT.
cask "weft" do
  version "0.9.2"

  on_macos do
    on_intel do
      sha256 "a6a861d1b4c3a4fbca457bcd69b9fbd4057bbe956a44f4ae8be25d189e24e596"
      url "https://github.com/HeoJeongBo/weft/releases/download/v#{version}/weft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "688af829b325c9624659df2b2ce3f1895ffcb25e15f0ecff2969a8c05bf2c41b"
      url "https://github.com/HeoJeongBo/weft/releases/download/v#{version}/weft_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b7a3236b1263865c9b07cf4cbd1a27a336234e960fc31407c53c7553cdbf9f99"
      url "https://github.com/HeoJeongBo/weft/releases/download/v#{version}/weft_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "847c66bfe1deb0bfebb17164f31b877ae85477d0954429902f6ab8007583986c"
      url "https://github.com/HeoJeongBo/weft/releases/download/v#{version}/weft_#{version}_linux_arm64.tar.gz"
    end
  end

  name "weft"
  desc "Orchestrate parallel Claude Code sessions across git worktrees + devcontainers"
  homepage "https://github.com/HeoJeongBo/weft"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "weft"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/weft"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    weft also needs Docker (Docker Desktop, OrbStack, or colima) and the
    Dev Container CLI, which are not Homebrew formulae:

      npm install -g @devcontainers/cli

    Run `weft doctor` to verify your environment.
  EOS
end
